function New-AIHtmlReport {
  param(
    [Parameter(Mandatory)]
    [pscustomobject]$Data,

    [Parameter(Mandatory)]
    [string]$OutPath
  )

  $tenant = $Data.tenant
  $generated = $Data.generated
  $apps = $Data.apps

  $total = $apps.Count
  $high = ($apps | Where-Object risk -eq "High").Count
  $medium = ($apps | Where-Object risk -eq "Medium").Count
  $low = ($apps | Where-Object risk -eq "Low").Count

  $rows = foreach ($a in $apps) {
    $riskClass = ($a.risk.ToLower())

@"
<tr>
  <td>
    $($a.name)
    <details>
      <summary>View details</summary>
      <ul>
        <li>Created: $($a.created)</li>
        <li>Consent Type: $($a.consentType)</li>
        <li>Last Sign-in: $($a.lastSignIn)</li>
        <li>Sign-ins (30 days): $($a.signIns30d)</li>
        <li>Conditional Access: $($a.conditionalAccess)</li>
      </ul>
    </details>
  </td>
  <td>$($a.appId)</td>
  <td>$($a.owners)</td>
  <td>$($a.permissions -join ", ")</td>
  <td class="$riskClass">$($a.risk)</td>
</tr>
"@
  }

  $jsonPretty = ($Data | ConvertTo-Json -Depth 10)

  $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Entra ID – AI Agent Monitoring Report</title>
<style>
  body { font-family: Segoe UI, Arial, sans-serif; margin: 30px; color: #111827; background-color: #ffffff; }
  h1, h2 { border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
  table { width: 100%; border-collapse: collapse; margin-top: 15px; }
  th, td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; vertical-align: top; }
  th { background-color: #f9fafb; font-weight: 600; }
  .high { color: #b91c1c; font-weight: bold; }
  .medium { color: #b45309; font-weight: bold; }
  .low { color: #166534; font-weight: bold; }
  details { margin-top: 6px; }
  pre { background-color: #f9fafb; padding: 12px; border: 1px solid #e5e7eb; overflow-x: auto; }
  footer { margin-top: 40px; font-size: 12px; color: #6b7280; }
</style>
</head>
<body>

<h1>AI Agent Monitoring Report</h1>

<p>
<strong>Tenant:</strong> $tenant<br>
<strong>Generated:</strong> $generated<br>
<strong>Source:</strong> Microsoft Entra ID (Graph)
</p>

<h2>Executive Summary</h2>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Total AI Applications</td><td>$total</td></tr>
  <tr><td>High Risk</td><td class="high">$high</td></tr>
  <tr><td>Medium Risk</td><td class="medium">$medium</td></tr>
  <tr><td>Low Risk</td><td class="low">$low</td></tr>
</table>

<h2>AI Application Inventory</h2>
<table>
  <tr>
    <th>Application Name</th>
    <th>App ID</th>
    <th>Owners</th>
    <th>Permissions</th>
    <th>Risk</th>
  </tr>
  $($rows -join "`n")
</table>

<h2>Raw JSON Output</h2>
<details>
  <summary>Show raw data</summary>
  <pre>$jsonPretty</pre>
</details>

<footer>
Generated by Entra AI Agent Monitor (PowerShell). Visibility only — no policy changes are enforced.
</footer>

</body>
</html>
"@

  $outDir = Split-Path $OutPath -Parent
  if (!(Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

  Set-Content -Path $OutPath -Value $html -Encoding UTF8
}
